// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type RevokedToken struct {
	Jti       uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID                uuid.UUID
	Email             string
	PasswordHash      string
	CreatedAt         time.Time
	TotalUrlShortened int32
}
